import 'package:freezed_annotation/freezed_annotation.dart';

part 'image_model.freezed.dart';

part 'image_model.g.dart';

/// --- Data Transfer Object (DTO) ---
/// This model is generated by `freezed` and `json_serializable`.
/// It maps directly to the API's JSON response to get the URL.
@freezed
abstract class ImageModel with _$ImageModel {
  const factory ImageModel({required String url}) = _ImageModel;

  const ImageModel._();

  /// Factory constructor to parse JSON
  factory ImageModel.fromJson(Map<String, dynamic> json) =>
      _$ImageModelFromJson(json);
}
